#!/usr/bin/env bash
# start-copilot-offline.sh  (generated by the DGX Demo dashboard)
# Wires the GitHub Copilot CLI to the local vLLM server in offline / airgapped
# mode, so the agent talks only to the on-device model. Re-generate from the
# dashboard "Copilot CLI" page to refresh the served model id.
set -euo pipefail

BASE_URL="http://127.0.0.1:8001/v1"

echo "==> Checking the local vLLM server at ${BASE_URL}/models ..."
if ! curl -fsS --max-time 5 "${BASE_URL}/models" >/dev/null 2>&1; then
  echo "ERROR: vLLM is not reachable at ${BASE_URL}." >&2
  echo "       Launch a model from the dashboard (Models vLLM) first." >&2
  exit 1
fi

command -v copilot >/dev/null 2>&1 || {
  echo "ERROR: 'copilot' CLI not found. Install: npm install -g @github/copilot" >&2
  exit 1
}

export COPILOT_PROVIDER_TYPE="openai"
export COPILOT_PROVIDER_BASE_URL="${BASE_URL}"
export COPILOT_PROVIDER_API_KEY="vllm"
export COPILOT_MODEL="phi-4-mini"
export COPILOT_OFFLINE="true"

echo "  COPILOT_PROVIDER_BASE_URL = ${COPILOT_PROVIDER_BASE_URL}"
echo "  COPILOT_MODEL             = ${COPILOT_MODEL}"
echo "  COPILOT_OFFLINE           = true"
echo

exec copilot "$@"
